### ISSUE TITLE
Rewriting URLs without patching 'mod' from tagRules.

### ISSUE THREAD

**Issue by weibeu** [webrecorder/wabac.js#22]
https://github.com/webrecorder/wabac.js/blob/b5c51843a8945d08e25f3cb5a07df97cc1a5dbd5/src/rewrite/index.js#L389-L396

I don't understand if there's any specific reason to not patch the value of 'mod' from `attrRules[attr.name]` in the URL which is being rewritten?
For instance the expect behavior is that `.../https://foobar.com/...` gets rewritten to `.../mp_/httpsp://foobar.com/...` however this is not the case.

Moreover, Pywb seems implementating the exact expected behavior where the 'mod' is being passed to the `_rewrite_url` method so that it can patch the 'mod' (mp_ in few cases) into the URL.
https://github.com/webrecorder/pywb/blob/54d8bccf4a4eebf305012d49cb7330eaddea9eba/pywb/rewrite/html_rewriter.py#L430-L432

**Comment by ikreymer** [comment]
Good question, sorry for late response! The reason is that the 'mod' doesn't change in the service worker, its always `<timestamp>mp_/`,
and so its set as part of the prefix:

https://github.com/webrecorder/wabac.js/blob/main/src/collection.js#L187

The reason is that, in pywb, the modifier is needed to determine if something is a js/css/iframe/etc... but in the service worker, this is provided (much more accurately) via [Request.destination](https://developer.mozilla.org/en-US/docs/Web/API/RequestDestination) so the modifier is actually ignored (except for id_ and wrkf_ to determine identity or worker context, which just toggle the rewriting to be disabled).
