### ISSUE TITLE
Use auto-js-ipfs (with fallback to js-ipfs)

### ISSUE THREAD

**Issue by RangerMauve** [webrecorder/wabac.js#80]
- import auto-js-ipfs in [ipfs.js](https://github.com/webrecorder/wabac.js/blob/main/src/ipfs.js)
- Attempt to detect agregore/kubo/etc before resorting to initializing a node

Question: Should we ever try initializing a node or should we always fall back to web3.storage?

**Comment by ikreymer** [comment]
We might not need `ipfs.js` at all anymore, as that was designed to wrap js-ipfs?

Instead, can probably just have `js-auto-ipfs` replace most of the logic in [IPFSRangeLoader](https://github.com/webrecorder/wabac.js/blob/main/src/blockloaders.js#L479).

Thinking auto-js-ipfs should in this case:
- detect if window.location.origin is already `ipfs://` (Agregore), in which case it should attempt to load directly?
- detect if window.location.origin is an existing ipfs gateway, in which case should try to load new CIDs from same gateway?
- use the default gateway otherwise.

**Comment by RangerMauve** [comment]
TODO: Add unit tests for IPFS BlockLoader

Maybe we can hardcode something and assume that we'll keep pinning it and that w2s.link will still be up.

**Comment by RangerMauve** [comment]
Closed by #82
